version: '3.8'

services:
  x-ui:
    image: enwaiax/x-ui:latest
    container_name: x-ui
    restart: always
    ports:
      - "12122:54321"    # 12122 on VPS → x-ui web panel
      - "40000-40100:40000-40100"  # Ports for Xray/VLESS clients (range)
    volumes:
      - ./xui-data:/etc/x-ui
    environment:
      - TZ=Asia/Colombo
